CNI_LOGFILE = 'ovn_cni.log'

DEFAULT_LROUTER_NAME = "k8s-router"
OVN_BRIDGE = "br-int"

CNI_VERSION = "0.1.0"
CNI_COMMAND = "CNI_COMMAND"
CNI_CONTAINER_ID = "CNI_CONTAINERID"
CNI_IFNAME = "CNI_IFNAME"
CNI_NETNS = "CNI_NETNS"
CNI_ARGS = "CNI_ARGS"
K8S_POD_NAME = "K8S_POD_NAME"
K8S_POD_NAMESPACE = "K8S_POD_NAMESPACE"
K8S_ISOLATION_ANN = 'net.alpha.kubernetes.io/network-isolation'

KUBELET_PORT = 10255

DEFAULT_ALLOW_ACL_PRIORITY = 9999
DEFAULT_ACL_PRIORITY = 1001

# Constants for policy events
NS_EVENT_PRIORITY = 10
POD_EVENT_PRIORITY = 20
NP_EVENT_PRIORITY = 30
LPORT_EVENT_PRIORITY = 40

LPORT_ADD = 'lport_add'
LPORT_DEL = 'lport_del'
POD_ADD = 'pod_add'
POD_DEL = 'pod_del'
POD_UPDATE = 'pod_update'
NP_ADD = 'network_policy_add'
NP_DEL = 'network_policy_delete'
NP_UPDATE = 'network_policy_update'
NS_UPDATE = 'namespace_update'

EVENT_PRIORITIES = {
    LPORT_ADD: LPORT_EVENT_PRIORITY,
    LPORT_DEL: LPORT_EVENT_PRIORITY,
    POD_ADD: POD_EVENT_PRIORITY,
    POD_DEL: POD_EVENT_PRIORITY,
    POD_UPDATE: POD_EVENT_PRIORITY,
    NP_ADD: NP_EVENT_PRIORITY,
    NP_DEL: NP_EVENT_PRIORITY,
    NP_UPDATE: NP_EVENT_PRIORITY,
    NS_UPDATE: NS_EVENT_PRIORITY
}
