CNI_LOGFILE = 'ovn_cni.log'

DEFAULT_LROUTER_NAME = "k8s-router"
OVN_BRIDGE = "br-int"

CNI_VERSION = "0.1.0"
CNI_COMMAND = "CNI_COMMAND"
CNI_CONTAINER_ID = "CNI_CONTAINERID"
CNI_IFNAME = "CNI_IFNAME"
CNI_NETNS = "CNI_NETNS"
CNI_ARGS = "CNI_ARGS"
K8S_POD_NAME = "K8S_POD_NAME"
K8S_POD_NAMESPACE = "K8S_POD_NAMESPACE"
K8S_ISOLATION_ANN = 'net.alpha.kubernetes.io/network-isolation'

KUBELET_PORT = 10255

DEFAULT_ACL_PRIORITY = 1001
